INSERT INTO locations (location_id, location_type, code, name, parent_location_id) VALUES
(1, 'Country', 'FR', 'France', NULL),
(2, 'Country', 'GB', 'United Kingdom', NULL),
(10, 'Region', 'FR-IDF', 'Île-de-France', 1),
(11, 'Region', 'FR-PAC', 'Provence-Alpes-Côte d’Azur', 1),
(12, 'Region', 'FR-ARA', 'Auvergne-Rhône-Alpes', 1),
(13, 'Region', 'GB-ENG', 'England', 2),
(20, 'Admin_area', 'FR-75', 'Paris', 10),
(21, 'Admin_area', 'FR-06', 'Alpes-Maritimes', 11),
(22, 'Admin_area', 'FR-69', 'Rhône', 12),
(23, 'Admin_area', 'FR-13', 'Bouches-du-Rhône', 11),
(24, 'Admin_area', 'GB-LND', 'London', 13),
(30, 'City', 'PAR', 'Paris', 20),
(31, 'City', 'NCE', 'Nice', 21),
(32, 'City', 'LYO', 'Lyon', 22),
(33, 'City', 'MRS', 'Marseille', 23),
(34, 'City', 'LON', 'London', 24),
(40, 'Airport', 'CDG', 'Paris Charles de Gaulle', 30),
(41, 'Airport', 'ORY', 'Paris Orly', 30),
(42, 'Airport', 'NCE', 'Nice Côte d’Azur', 31),
(43, 'Airport', 'LYS', 'Lyon–Saint Exupéry', 32),
(44, 'Airport', 'MRS', 'Marseille Provence', 33),
(45, 'Airport', 'LGW', 'London Gatwick', 34),
(46, 'Airport', 'LHR', 'London Heathrow', 34),
(47, 'Airport', 'LCY', 'London City Airport', 34);